# Generated by Django 4.2 on 2023-04-23 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('abstract', models.TextField()),
                ('year', models.IntegerField()),
                ('source_id', models.IntegerField()),
                ('work_type', models.CharField(max_length=500)),
                ('raw_keywords', models.CharField(max_length=500)),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extraction_app.advisor')),
            ],
        ),
    ]
